spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy : ant_path_matcher
springdoc:
  api-docs:
    path : /api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port : 8080

management:
  endpoints:
    web:
      exposure:
        include: health
